### ISSUE TITLE
Where are the asset .obj files?

### ISSUE THREAD

**Issue by ramiss** [wislon/arcore-sample#2]
Hi,  I really appreciate you cleaning up the mess that was the original HelloAR.  

For anyone interested, the Asset\*.obj files are missing. You can get them from here:
https://github.com/xamarin/XamarinComponents/tree/master/Android/ARCore/samples/HelloAR/Assets

**Comment by wislon** [comment]
Thanks for tracking them down @ramiss! I'm sorry it took so long to get back to you. I'll put a pointer to them in the readme, too. Cheers 👍
